namespace Magpie.App {
	runtimeclass NewApplicationViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		NewApplicationViewModel(Int32 profileIdx);

		void PrepareForOpen(UInt32 dpi, Boolean isLightTheme, Windows.UI.Core.CoreDispatcher dispatcher);

		IVector<IInspectable> CandidateWindows { get; };
		Int32 CandidateWindowIndex;
		String Name;
		IVector<IInspectable> Profiles { get; };
		Int32 CopyFromProfileIndex;
		Boolean IsCreatingProfile { get; };
		Boolean IsConfirmButtonEnabled { get; };
		Boolean IsNoCandidateWindow { get; };
		Boolean IsAnyCandidateWindow { get; };

		void Confirm();
	}
}
