namespace Magpie.App {
	runtimeclass RootPage : Windows.UI.Xaml.Controls.Page {
		RootPage();

		Microsoft.UI.Xaml.Controls.NavigationView RootNavigationView { get; };
		TitleBarControl TitleBar { get; };

		NewApplicationViewModel NewApplicationViewModel { get; };

		void NavigateToAboutPage();

		void ShowToast(String message);
	}
}
